services:

  # go-app:
  #   container_name: go-app
  #   build: 
  #     context: ./ # Use an image built from the specified dockerfile in the current directory.
  #     dockerfile: Dockerfile
  #   image: go-app:latest
  #   # volumes:
  #   #   - ./app:/app
  #   ports:
  #     - 8888:8888

  postgres_go:
    container_name: postgres_go
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=golang_test
  
  adminer_go:
    container_name: adminer_go
    image: adminer:latest
    ports:
      - 8080:8080